// Code generated by generate_unit_tests.go. DO NOT EDIT.
// This file contains a unit test for every functionality test (found in filesystem_tests.go).
// Generated at Wed May 2 5:12:32 PM.

package memoryFS

import "testing"
import "fsraft"

func TestMemoryFS_TestOpenClose(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        fsraft.TestOpenClose(t, &mfs)
}

func TestMemoryFS_TestBasicReadWrite(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        fsraft.TestBasicReadWrite(t, &mfs)
}

