// Code generated by generate_unit_tests.go. DO NOT EDIT.
// This file contains a unit test for every functionality test (found in filesystem_tests.go).
// Generated at Tue May 8 7:36:50 AM.

package memoryFS

import "filesystem"
import "testing"

func TestMemoryFS_TestOpenRWClose4(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenRWClose4(t, &mfs)
}

func TestMemoryFS_TestWriteRead8Bytes(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestWriteRead8Bytes(t, &mfs)
}

func TestMemoryFS_TestBasicOpenClose(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestBasicOpenClose(t, &mfs)
}

func TestMemoryFS_TestOpenOpened(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenOpened(t, &mfs)
}

func TestMemoryFS_TestMkdirTree(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestMkdirTree(t, &mfs)
}

func TestMemoryFS_TestOpenAlreadyExists(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenAlreadyExists(t, &mfs)
}

func TestMemoryFS_TestWrite1KBytes(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestWrite1KBytes(t, &mfs)
}

func TestMemoryFS_TestWrite10MBytes(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestWrite10MBytes(t, &mfs)
}

func TestMemoryFS_TestOpenROClose64(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenROClose64(t, &mfs)
}

func TestMemoryFS_TestReadWriteBasic4(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestReadWriteBasic4(t, &mfs)
}

func TestMemoryFS_TestWrite100MBytes(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestWrite100MBytes(t, &mfs)
}

func TestMemoryFS_TestReadClosedFile(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestReadClosedFile(t, &mfs)
}

func TestMemoryFS_TestWriteRead1Byte(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestWriteRead1Byte(t, &mfs)
}

func TestMemoryFS_TestMkdir(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestMkdir(t, &mfs)
}

func TestMemoryFS_TestOpenCloseDeleteMaxFD(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenCloseDeleteMaxFD(t, &mfs)
}

func TestMemoryFS_TestSeekOffEOF(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestSeekOffEOF(t, &mfs)
}

func TestMemoryFS_TestOpenRWClose64(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenRWClose64(t, &mfs)
}

func TestMemoryFS_TestOpenCloseLeastFD(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenCloseLeastFD(t, &mfs)
}

func TestMemoryFS_TestWrite1MBytes(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestWrite1MBytes(t, &mfs)
}

func TestMemoryFS_TestOpenCloseDeleteAcrossDirectories(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenCloseDeleteAcrossDirectories(t, &mfs)
}

func TestMemoryFS_TestDeleteNotFound(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestDeleteNotFound(t, &mfs)
}

func TestMemoryFS_TestOpenRWClose(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenRWClose(t, &mfs)
}

func TestMemoryFS_TestOpenCloseDeleteRoot(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenCloseDeleteRoot(t, &mfs)
}

func TestMemoryFS_TestWrite1Byte(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestWrite1Byte(t, &mfs)
}

func TestMemoryFS_TestWriteClosedFile(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestWriteClosedFile(t, &mfs)
}

func TestMemoryFS_TestOpenROClose4(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenROClose4(t, &mfs)
}

func TestMemoryFS_TestReadWriteBasic(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestReadWriteBasic(t, &mfs)
}

func TestMemoryFS_TestOpenROClose(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenROClose(t, &mfs)
}

func TestMemoryFS_TestOpenCloseDeleteRootMax(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenCloseDeleteRootMax(t, &mfs)
}

func TestMemoryFS_TestSeekErrorBadFD(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestSeekErrorBadFD(t, &mfs)
}

func TestMemoryFS_TestSeekErrorBadOffsetOperation(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestSeekErrorBadOffsetOperation(t, &mfs)
}

func TestMemoryFS_TestWrite8Bytes(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestWrite8Bytes(t, &mfs)
}

func TestMemoryFS_TestCloseClosed(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestCloseClosed(t, &mfs)
}

func TestMemoryFS_TestOpenNotFound(t *testing.T) {
	mfs := CreateEmptyMemoryFS()
        filesystem.TestOpenNotFound(t, &mfs)
}

