// Code generated by generate_unit_tests.go. DO NOT EDIT.
// This file contains a unit test for every combination of functionality test
// (found in filesystem_tests.go) and difficulty (found in difficulties.go).
// Generated at Thu May 10 11:06:25 AM.

package fsraft

import "filesystem"
import "testing"

func TestClerk_OneClerkThreeServersNoErrors_TestSeekErrorBadOffsetOperation(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestSeekErrorBadOffsetOperation, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestSeekOffEOF(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestSeekOffEOF, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestRndWriteRead64BytesSimple(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead64BytesSimple, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestCannotDeleteRootDir(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestCannotDeleteRootDir, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestDeleteNotFound(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestDeleteNotFound, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestCloseClosed(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestCloseClosed, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenNotFound(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenNotFound, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenROClose(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenROClose, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestMkdir(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestMkdir, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestMkdirNotFound(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestMkdirNotFound, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestWrite1Byte(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWrite1Byte, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestWriteClosedFile(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWriteClosedFile, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestCannotReadFromWriteOnly(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestCannotReadFromWriteOnly, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestRndWriteRead8BytesIter8(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead8BytesIter8, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestSeekErrorBadFD(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestSeekErrorBadFD, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestWriteReadBasic4(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWriteReadBasic4, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestMkdirNotFound(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestMkdirNotFound, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenOffsetEqualsZero(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenOffsetEqualsZero, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenAppend(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenAppend, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestCannotWriteToReadOnly(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestCannotWriteToReadOnly, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestRndWriteRead8BytesIter64(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead8BytesIter64, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestRndWriteRead64KBIter1MB(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead64KBIter1MB, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenCloseLeastFD(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenCloseLeastFD, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestMkdirTree(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestMkdirTree, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenAppend(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenAppend, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestSeekOffEOF(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestSeekOffEOF, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestWriteClosedFile(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWriteClosedFile, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestWrite1MBytes(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWrite1MBytes, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestBasicOpenClose(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestBasicOpenClose, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestWrite10MBytes(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWrite10MBytes, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestRndWriteRead64BytesIter64K(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead64BytesIter64K, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenOpened(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenOpened, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestCannotWriteToReadOnly(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestCannotWriteToReadOnly, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestWrite10MBytes(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWrite10MBytes, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestRndWriteRead1ByteSimple(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead1ByteSimple, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestRndWriteRead1MBIter100MB(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead1MBIter100MB, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenTruncate(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenTruncate, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestRndWriteRead8BytesIter64(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead8BytesIter64, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestRndWriteRead64KBIter1MB(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead64KBIter1MB, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenCloseDeleteAcrossDirectories(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenCloseDeleteAcrossDirectories, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenRWClose(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenRWClose, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestWrite1Byte(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWrite1Byte, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestReadClosedFile(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestReadClosedFile, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestWriteSomeButNotAll(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWriteSomeButNotAll, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestRndWriteReadVerfiyHoleExpansion(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteReadVerfiyHoleExpansion, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenRWClose64(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenRWClose64, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenCloseDeleteMaxFD(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenCloseDeleteMaxFD, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenRWClose64(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenRWClose64, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestDeleteNotFound(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestDeleteNotFound, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenROClose4(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenROClose4, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenCloseDeleteRoot(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenCloseDeleteRoot, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenCloseDeleteRootMax(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenCloseDeleteRootMax, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenCloseLeastFD(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenCloseLeastFD, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestSeekErrorBadFD(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestSeekErrorBadFD, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestRndWriteRead8BytesIter8(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead8BytesIter8, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestHelpGenerateJenkinsPipeline(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestHelpGenerateJenkinsPipeline, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestRndWriteRead64BytesIter64K(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead64BytesIter64K, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenNotFound(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenNotFound, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenROClose64(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenROClose64, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestHelpGenerateJenkinsPipeline(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestHelpGenerateJenkinsPipeline, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenCloseDeleteRootMax(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenCloseDeleteRootMax, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestWrite1KBytes(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWrite1KBytes, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestMkdir(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestMkdir, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestRndWriteReadVerfiyHoleExpansion(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteReadVerfiyHoleExpansion, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenOpened(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenOpened, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestRndWriteRead1ByteSimple(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead1ByteSimple, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestBasicOpenClose(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestBasicOpenClose, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenAlreadyExists(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenAlreadyExists, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenROClose64(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenROClose64, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenTruncate(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenTruncate, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestWriteReadBasic(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWriteReadBasic, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestWriteReadBasic4(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWriteReadBasic4, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestWrite1MBytes(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWrite1MBytes, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestCannotDeleteRootDir(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestCannotDeleteRootDir, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenCloseDeleteMaxFD(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenCloseDeleteMaxFD, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenOffsetEqualsZero(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenOffsetEqualsZero, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestReadClosedFile(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestReadClosedFile, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestRndWriteRead64KBIter10MB(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead64KBIter10MB, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestMkdirAlreadyExists(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestMkdirAlreadyExists, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestSeekErrorBadOffsetOperation(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestSeekErrorBadOffsetOperation, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestWriteSomeButNotAll(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWriteSomeButNotAll, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestCloseClosed(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestCloseClosed, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestRndWriteRead8BytesSimple(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead8BytesSimple, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenCloseDeleteRoot(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenCloseDeleteRoot, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestCannotReadFromWriteOnly(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestCannotReadFromWriteOnly, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestWrite8Bytes(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWrite8Bytes, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenCloseDeleteAcrossDirectories(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenCloseDeleteAcrossDirectories, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenROClose4(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenROClose4, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenRWClose4(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenRWClose4, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestWrite1KBytes(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWrite1KBytes, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestWrite100MBytes(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWrite100MBytes, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestMkdirTree(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestMkdirTree, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenRWClose4(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenRWClose4, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestRndWriteRead64BytesSimple(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead64BytesSimple, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenRWClose(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenRWClose, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestWriteReadBasic(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWriteReadBasic, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestWrite8Bytes(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWrite8Bytes, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestRndWriteRead8BytesSimple(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead8BytesSimple, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestRndWriteRead1MBIter100MB(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead1MBIter100MB, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestOpenROClose(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenROClose, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestWrite100MBytes(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestWrite100MBytes, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestRndWriteRead64KBIter10MB(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestRndWriteRead64KBIter10MB, OneClerkFiveServersErrors)
}

func TestClerk_OneClerkThreeServersNoErrors_TestOpenAlreadyExists(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestOpenAlreadyExists, OneClerkThreeServersNoErrors)
}

func TestClerk_OneClerkFiveServersErrors_TestMkdirAlreadyExists(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, filesystem.TestMkdirAlreadyExists, OneClerkFiveServersErrors)
}

