// Code generated by generate_unit_tests.go. DO NOT EDIT.
// This file contains a unit test for every combination of functionality test
// (found in filesystem_tests.go) and difficulty (found in test_setup.go).
// Generated at Wed May 2 6:23:11 PM.

package fsraft

import "testing"

func TestClerk_TestOpenCloseBasic_OneClerkFiveServersNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestOpenCloseBasic, OneClerkFiveServersNoErrors)
}

func TestClerk_TestOpenROClose_OneClerkFiveServersNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestOpenROClose, OneClerkFiveServersNoErrors)
}

func TestClerk_TestOpenRWClose_OneClerkFiveServersNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestOpenRWClose, OneClerkFiveServersNoErrors)
}

func TestClerk_TestOpenRWClose4_OneClerkOneServerNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestOpenRWClose4, OneClerkOneServerNoErrors)
}

func TestClerk_TestReadWriteBasic_OneClerkOneServerNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestReadWriteBasic, OneClerkOneServerNoErrors)
}

func TestClerk_TestOpenROClose4_OneClerkOneServerNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestOpenROClose4, OneClerkOneServerNoErrors)
}

func TestClerk_TestOpenCloseBasic_OneClerkOneServerNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestOpenCloseBasic, OneClerkOneServerNoErrors)
}

func TestClerk_TestOpenROClose_OneClerkOneServerNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestOpenROClose, OneClerkOneServerNoErrors)
}

func TestClerk_TestOpenROClose4_OneClerkFiveServersNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestOpenROClose4, OneClerkFiveServersNoErrors)
}

func TestClerk_TestOpenRWClose_OneClerkOneServerNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestOpenRWClose, OneClerkOneServerNoErrors)
}

func TestClerk_TestOpenRWClose4_OneClerkFiveServersNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestOpenRWClose4, OneClerkFiveServersNoErrors)
}

func TestClerk_TestReadWriteBasic_OneClerkFiveServersNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestReadWriteBasic, OneClerkFiveServersNoErrors)
}

func TestClerk_TestReadWriteBasic4_OneClerkOneServerNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestReadWriteBasic4, OneClerkOneServerNoErrors)
}

func TestClerk_TestReadWriteBasic4_OneClerkFiveServersNoErrors(t *testing.T) {
	runFunctionalityTestWithDifficulty(t, TestReadWriteBasic4, OneClerkFiveServersNoErrors)
}

